Feature/registration forms
Lambda-School-Labs/LabsPT12-Express_Groomer-TeamA-FE pull request #12
Opened 2020-11-02 05:51 UTC by luisabellan

2020-11-02 23:50 UTC, coryortega commented on .env.sample
> +REACT_APP_API_URI=https://labspt12-express-groomer-a-api.herokuapp.com/
Need to remove .env.sample file

2020-11-03 00:02 UTC, coryortega requested changes
Nice job, just need to remove .env.sample file and also delete comments, refactor class component to functional component

2020-11-03 00:02 UTC, coryortega commented on src/components/Forms/Register.js
> +export default Register;
Not entirely necessary, but could be converted to functional component

2020-11-03 00:02 UTC, coryortega commented on src/components/Layouts/Navbar.js
> +export default Navbar;
Navbar might not be necessary, now that William implemented an Ant design dashboard with a nav on the side

2020-11-03 00:02 UTC, coryortega commented on src/components/Forms/RegisterCustomer.js
> +  //     })
While I think the comments are nice so Adella can see the changes made, we ultimately should delete them before merging to main

2020-11-04 05:46 UTC, luisabellan commented on .env.sample
> +REACT_APP_API_URI=https://labspt12-express-groomer-a-api.herokuapp.com/
done :+1:

2020-11-04 05:54 UTC, luisabellan commented on src/components/Forms/Register.js
> +export default Register;
done :+1:

2020-11-04 09:50 UTC, luisabellan commented on src/components/Layouts/Navbar.js
> +export default Navbar;
removed

2020-11-04 09:54 UTC, luisabellan commented on src/components/Forms/RegisterCustomer.js
> +  //     })
done

2020-11-04 09:55 UTC, luisabellan commented
> Nice job, just need to remove .env.sample file and also delete comments, refactor class component to functional component

There must be something wrong on the tests, because it requires that there is a .env.sample file:
https://gyazo.com/f0dc2fe8bd39703aecc29d44ae5a1c73

2020-11-04 10:19 UTC, luisabellan reviewed
.env.sample must be present so it can be copied into .env to recreate it (cp .env.sample .env)

2020-11-16 00:04 UTC, closed without merging