created branch
Lambda-School-Labs/LabsPT12-Express_Groomer-TeamA-FE pull request #43
Opened 2020-12-15 00:50 UTC by taylorpalmer

2020-12-17 01:52 UTC, taylorpalmer commented
Need to get individual groomer card to display after selecting.

2020-12-19 14:44 UTC, SRattacasa requested changes
The SearchForm file being changed here is **much** older and different than the current one. To help avoid merge conflicts, let's sync up via Zoom/standup and figure out what changes need to be applied, and add the appropriate code to that component. 

(The alternative for time's sake would be if someone wants to review our PR for the searchform, then make changes to it afterwards).

2021-01-05 01:59 UTC, SRattacasa approved these changes

2021-01-05 02:03 UTC, Garuda27 approved these changes

2021-01-05 02:03 UTC, merged