Feature/calendar
Lambda-School-Labs/LabsPT12-Express_Groomer-TeamA-FE pull request #53
Opened 2021-01-07 02:29 UTC by guivecchi12

Currently just a calendar display, there is no real functionality

2021-01-12 01:21 UTC, coryortega approved these changes

2021-01-12 01:37 UTC, taylorpalmer requested changes
Great work on this. I left a comment regarding some redundant booleans for Groomer. I saw it in three places. There were also several "defined but never used" errors. I don't know if that was from something you wrote but we might consider doing a sweep for dead variables.

2021-01-12 01:37 UTC, taylorpalmer commented on src/components/customers/CustomerDashboard/CustomerDashboardContainer.js
> +    setGroomer(false);
We're setting Groomer to false twice here. Delete?

2021-01-13 01:43 UTC, guivecchi12 commented
Good catch Taylor, I removed the duplicates

2021-01-13 01:58 UTC, taylorpalmer approved these changes

2021-01-13 02:00 UTC, merged