Began psuedocode for filter logc options
Lambda-School-Labs/LabsPT12-Express_Groomer-TeamA-FE pull request #54
Opened 2021-01-12 01:27 UTC by SRattacasa

2021-01-12 02:33 UTC, SRattacasa commented
- Built the switch case logic but commented it out for now
- It validates if the dogFilter or catFilter are true/false, and if true, or if both are true, it will add the groomer to the filtered array
- If not, it shouldn't 
- That array is then later sorted for distance based upon the search zipcode/location data

2021-01-24 13:35 UTC, SRattacasa commented
- useEffect hook to load groomers was failing at times
- Updated the getGroomerData() function in the api/index.js file to be async
- Haven't had the issue since

2021-01-24 14:30 UTC, SRattacasa commented
- Updated and validated the switch case logic
- Applies the proper filter to the results
- Conditionally renders a text statement about the animals groomed if the dogs or cats filter is true

2021-01-26 00:44 UTC, SRattacasa commented
- Added states for the checkboxes to update when checked
- Using the states to reset the form by adding setState(false) to the reset button onChange handler
- Removed a lot of old code that was not in use after testing/verifying 
- Verified conditional render logic is working for animals serviced

2021-01-26 02:27 UTC, taylorpalmer reviewed
Looks good. Because I'm not familiar, I just want confirmation that we won't miss the err handling etcetera that was removed before I approve.

2021-01-26 02:27 UTC, taylorpalmer commented on src/components/search/SearchForm.js
>    };
Your dog/cat logic looks great! But do we not need these lines 81-88?

2021-01-27 01:06 UTC, coryortega requested changes
Remove unused variables

2021-01-27 01:06 UTC, coryortega commented on src/components/search/SearchForm.js
>    const [name, setName] = useState('');
Great work, remove unused variables and we're all good!

2021-01-28 02:19 UTC, coryortega approved these changes
Nice work! Clean code, nice use of switch cases

2021-01-28 02:19 UTC, coryortega commented on src/components/search/SearchForm.js
> +
Nice use of switch cases!

2021-01-28 02:21 UTC, AustinKelsay approved these changes

2021-01-28 02:38 UTC, merged